name: deploy railways

on:
  push:
    branches:
      - main
jobs:
  build:
    if: github.repository == 'reportik/reflex-template'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4    
          
      - name: deploy
        uses: bervProject/railway-deploy@main
        with:
          railway_token: "ae4ab7b0-fe9f-4fba-9799-ee2d5366151a"
          service: "invtek.up.railway.app"
        




