name: deploy railways

on:
  push:
    branches:
      - main
jobs:
  build:
    if: github.repository == 'reportik/reflex-template'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4    
          
      - name: deploy
        uses: bervProject/railway-deploy@main
        with:
          railway_token: "d2f04e36-5a9d-48c2-8567-0ba5a772660a"
          service: "my-service"
        




