name: Static Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nix
        run: curl -L https://nixos.org/nix/install | sh -s -- --no-daemon

      - name: Install Nix Packs
        run: |
          curl -L https://github.com/nixpacks/nixpacks/releases/latest/download/install.sh | sh

      - name: Build with Nix Packs
        run: nixpacks build
