name: Static Build

on:
  push:
    branches:
      - main
jobs:
  build:
    if: github.repository == 'reportik/reflex-template'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nix Packs
        run: |
          curl -sSL https://nixpacks.com/install.sh | bash

      - name: Build with Nix Packs
        run: nixpacks build ./
      
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update static build
        
